### ISSUE TITLE
Sign up bug on project. FindOrCreate is undefined

### ISSUE THREAD

**Issue by JuanR9910** [WDI-SEA/project-4-issues#7]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
Postgres, psql, Express, Nodejs
### What's the problem you're trying to solve?
I attempted to sign up an account on my app to check if it's in working order but I get this "findOrCreate is undefined" error. My nodeman said the error was in the auth.js but I cannot find the problem. Instructor Tom couldn't figure out the problem either. 

### Post any code you think might be relevant (one fenced block per file)
Here is the auth.js file:
```const express = require('express')```
`const router = express.Router()`
`const db = require('../models')`
`const passport = require('../config/ppConfig.js')`

`router.get('/signup', (req, res)=>{`
    `res.render('auth/signup')`
`})`

`router.post('/signup', (req, res)=>{`
    `console.log(req.body.email)`
   ` db.user.findOrCreate({`
       ` where: {email: req.body.email},`
        `defaults: {`
            `name: req.body.name,`
           ` password: req.body.password`
       ` }`
    `})`
    `.then(([createdUser, wasCreated])=>{`
        `if(wasCreated){`
            `console.log(`just created the following user:`, createdUser)`
            `// res.send('POST form data from signup.ejs, then redirect')`
            `passport.authenticate('local', {`
                `successRedirect: '/', // !-> FLASH <-!`
                `successFlash: 'Account created and logged in!'`
            `}) // why does this need to be an IIFE???`
            `(req, res)`
        `} else { // !-> FLASH <-!`
            `req.flash('error', 'email already exists, try logging in')` 
            `// console.log('An account associated with that email address already exists! Did you mean to login?')`
            `res.redirect('/auth/login')`
        `}`
   `})`
    `.catch(err =>{ // !-> FLASH <-!`
        `req.flash('error', err.message)` 
        `res.redirect('/auth/signup')`
    `})`
`})`

`router.get('/login', (req, res)=>{`
    `res.render('auth/login')`
`})`

`router.post('/login', passport.authenticate('local', {`
        `failureRedirect: '/auth/login',`
        `successRedirect: '/', // !-> FLASH <-!`
        `failureFlash: 'Invalid username and/or password.',`
        `successFlash: 'You are now logged in.'`
    `})`
`)`

`router.get('/logout', (req, res)=>{`
    `req.logout() // !-> FLASH <-!`
    `req.flash('Success! You\'re logged out.')`
    `res.redirect('/')`
`})`

`module.exports = router;`
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
TypeError: Cannot read property 'findOrCreate' of undefined
    at router.post (/mnt/c/Users/juanr/sei_pumpkin_smashers/project-2-Game-Review/controllers/auth.js:12:13)
    at Layer.handle [as handle_request] (/mnt/c/Users/juanr/sei_pumpkin_smashers/project-2-Game-Review/node_modules/express/lib/router/layer.js:95:5)
    at next (/mnt/c/Users/juanr/sei_pumpkin_smashers/project-2-Game-Review/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/mnt/c/Users/juanr/sei_pumpkin_smashers/project-2-Game-Review/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/mnt/c/Users/juanr/sei_pumpkin_smashers/project-2-Game-Review/node_modules/express/lib/router/layer.js:95:5)
    at /mnt/c/Users/juanr/sei_pumpkin_smashers/project-2-Game-Review/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/mnt/c/Users/juanr/sei_pumpkin_smashers/project-2-Game-Review/node_modules/express/lib/router/index.js:341:12)
    at next (/mnt/c/Users/juanr/sei_pumpkin_smashers/project-2-Game-Review/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/mnt/c/Users/juanr/sei_pumpkin_smashers/project-2-Game-Review/node_modules/express/lib/router/index.js:174:3)
    at router (/mnt/c/Users/juanr/sei_pumpkin_smashers/project-2-Game-Review/node_modules/express/lib/router/index.js:47:12)

### What is your best guess as to the source of the problem?


### What things have you already tried to solve the problem?

**Comment by timmshinbone** [comment]
Did this get resolved yet?

**Comment by JuanR9910** [comment]
Nope
